# Project information
site_name: 'Drupal Documentation'
site_description: 'A useful collection of Drupal related tasks.'
repo_name: 'GitHub'
repo_url: 'https://github.com/my-github-handle/my-project'

# Pages
pages:
    - Home: index.md
    - Local Setup: local-setup.md
    - Drush: drush.md
    - Using MkDocs: using-mkdocs.md

# Copyright
copyright: 'Copyright (c)'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  version: '0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'light-blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
